//------------------------------------------------------------------------
// Copyright(c) 2025 shiroyoru.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http ://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"RedHusky.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"RedHusky VST3 (64Bit)"
#else
#define stringFileDescription	"RedHusky VST3"
#endif
#define stringCompanyName		"shiroyoru\0"
#define stringLegalCopyright	"Copyright(c) 2024 shiroyoru."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
