//------------------------------------------------------------------------
// Copyright(c) 2025 shiroyoru.
//
// This program is free software : you can redistribute it and /or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// You should have received a copy of the GNU General Public License
// along with this program.If not, see < https://www.gnu.org/licenses/>.
// 
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"RedHusky.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"RedHusky VST3 (64Bit)"
#else
#define stringFileDescription	"RedHusky VST3"
#endif
#define stringCompanyName		"shiroyoru\0"
#define stringLegalCopyright	"Copyright(c) 2024 shiroyoru."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
